import requests
from bs4 import BeautifulSoup
import json
import time
import os
from datetime import datetime

# Daftar agent yang mau dipantau
AGENTS = [
    {"id": 22524, "name": "Quantiva Intelligence"},
    {"id": 22497, "name": "Nexora Analytics AI"},
    {"id": 22455, "name": "DataQuant Pro"},
    {"id": 22300, "name": "DataAnalyst Pro"},
    {"id": 22398, "name": "InsightForge AI"},
    {"id": 30502, "name": "StoryWeaver AI"},
    # StoryWeaver AI belum punya ID, nanti tambahkan setelah mint
]

def scrape_agent(agent_id, agent_name):
    """Scrape data dari halaman 8004scan agent"""
    url = f"https://8004scan.io/agents/base/{agent_id}"
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
    
    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Extract Overall Score
        overall_score = "N/A"
        score_elem = soup.find('div', string=lambda x: x and 'Overall Score' in x)
        if score_elem:
            parent = score_elem.find_parent()
            value = parent.find(class_=lambda x: x and ('value' in x or 'score' in x.lower()))
            if value:
                overall_score = value.text.strip()
        
        # Extract Total Feedback
        feedback_count = "N/A"
        feedback_elem = soup.find('div', string=lambda x: x and 'Total Feedback' in x)
        if feedback_elem:
            parent = feedback_elem.find_parent()
            value = parent.find(class_=lambda x: x and ('value' in x or 'count' in x.lower()))
            if value:
                feedback_count = value.text.strip()
        
        # Extract Rank
        rank = "N/A"
        rank_elem = soup.find('div', string=lambda x: x and 'Rank' in x)
        if rank_elem:
            parent = rank_elem.find_parent()
            value = parent.find(class_=lambda x: x and ('value' in x or 'rank' in x.lower()))
            if value:
                rank = value.text.strip()
        
        return {
            "name": agent_name,
            "id": agent_id,
            "overall_score": overall_score,
            "feedback_count": feedback_count,
            "rank": rank,
            "last_updated": datetime.now().isoformat(),
            "status": "success"
        }
        
    except Exception as e:
        return {
            "name": agent_name,
            "id": agent_id,
            "error": str(e),
            "status": "failed",
            "last_updated": datetime.now().isoformat()
        }

def generate_markdown(stats):
    """Generate markdown report dari data"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    markdown = f"""# 📊 Agent Stats Report

**Last Update:** {timestamp}

| Agent | Overall Score | Total Feedback | Rank | Status |
|-------|---------------|----------------|------|--------|
"""
    
    for stat in stats:
        if stat['status'] == 'success':
            markdown += f"| {stat['name']} | {stat['overall_score']} | {stat['feedback_count']} | {stat['rank']} | ✅ |\n"
        else:
            markdown += f"| {stat['name']} | - | - | - | ❌ {stat.get('error', 'Unknown')[:30]} |\n"
    
    markdown += f"""
---
<sub>Auto-generated by GitHub Actions • {timestamp}</sub>
"""
    return markdown

def generate_json(stats):
    """Generate JSON report"""
    return json.dumps({
        "timestamp": datetime.now().isoformat(),
        "agents": stats
    }, indent=2)

def main():
    print(f"Starting scrape for {len(AGENTS)} agents...")
    
    results = []
    for agent in AGENTS:
        print(f"Scraping {agent['name']} (ID: {agent['id']})...")
        result = scrape_agent(agent['id'], agent['name'])
        results.append(result)
        time.sleep(2)  # Delay untuk menghindari rate limit
    
    # Generate reports
    markdown_report = generate_markdown(results)
    json_report = generate_json(results)
    
    # Save to files
    with open('STATS.md', 'w', encoding='utf-8') as f:
        f.write(markdown_report)
    
    with open('stats.json', 'w', encoding='utf-8') as f:
        f.write(json_report)
    
    print("✅ Reports generated: STATS.md and stats.json")
    print("\n" + markdown_report)

if __name__ == "__main__":
    main()
