import requests
from bs4 import BeautifulSoup
import json
import time
import os
from datetime import datetime

# Daftar agent yang mau dipantau (SUDAH TERMASUK STORYWEAVER)
AGENTS = [
    {"id": 22524, "name": "Quantiva Intelligence"},
    {"id": 22497, "name": "Nexora Analytics AI"},
    {"id": 22455, "name": "DataQuant Pro"},
    {"id": 22300, "name": "DataAnalyst Pro"},
    {"id": 22398, "name": "InsightForge AI"},
    {"id": 30502, "name": "StoryWeaver AI"},  # <-- WAJIB ADA
]

def scrape_agent(agent_id, agent_name):
    """Scrape data dari halaman 8004scan agent"""
    url = f"https://8004scan.io/agents/base/{agent_id}"
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
    
    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # === Extract Overall Score ===
        overall_score = "N/A"
        # Cari elemen yang mengandung teks "Overall Score"
        score_label = soup.find(['div', 'p', 'span'], string=lambda x: x and 'Overall Score' in x)
        if score_label:
            parent = score_label.find_parent()
            # Cari nilai di sibling atau child
            value_elem = parent.find(class_=lambda x: x and ('value' in x or 'score' in x.lower()))
            if value_elem:
                overall_score = value_elem.text.strip()
        
        # === Extract Total Feedback ===
        feedback_count = "N/A"
        fb_label = soup.find(['div', 'p', 'span'], string=lambda x: x and 'Total Feedback' in x)
        if fb_label:
            parent = fb_label.find_parent()
            value_elem = parent.find(class_=lambda x: x and ('value' in x or 'count' in x.lower()))
            if value_elem:
                feedback_count = value_elem.text.strip()
        
        # === Extract Rank ===
        rank = "N/A"
        rank_label = soup.find(['div', 'p', 'span'], string=lambda x: x and 'Rank' in x)
        if rank_label:
            parent = rank_label.find_parent()
            value_elem = parent.find(class_=lambda x: x and ('value' in x or 'rank' in x.lower()))
            if value_elem:
                rank = value_elem.text.strip()
        
        return {
            "name": agent_name,
            "id": agent_id,
            "overall_score": overall_score,
            "feedback_count": feedback_count,
            "rank": rank,
            "last_updated": datetime.now().isoformat(),
            "status": "success"
        }
        
    except Exception as e:
        print(f"⚠️ Error scraping {agent_name}: {str(e)}")
        return {
            "name": agent_name,
            "id": agent_id,
            "error": str(e),
            "status": "failed",
            "last_updated": datetime.now().isoformat()
        }

def generate_markdown(stats):
    """Generate markdown report dari data"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    markdown = f"""# 📊 Agent Stats Report

**Last Update:** {timestamp} (UTC)

| Agent | Agent ID | Overall Score | Total Feedback | Rank | Status |
|-------|----------|---------------|----------------|------|--------|
"""
    
    for stat in stats:
        if stat['status'] == 'success':
            markdown += f"| {stat['name']} | {stat['id']} | {stat['overall_score']} | {stat['feedback_count']} | {stat['rank']} | ✅ |\n"
        else:
            markdown += f"| {stat['name']} | {stat['id']} | - | - | - | ❌ Error |\n"
    
    markdown += f"""
---
<sub>Auto-generated by GitHub Actions • {timestamp} UTC</sub>
"""
    return markdown

def generate_json(stats):
    """Generate JSON report"""
    return json.dumps({
        "timestamp": datetime.now().isoformat(),
        "total_agents": len(stats),
        "agents": stats
    }, indent=2)

def main():
    print(f"🚀 Starting scrape for {len(AGENTS)} agents...")
    
    results = []
    for agent in AGENTS:
        print(f"📡 Scraping {agent['name']} (ID: {agent['id']})...")
        result = scrape_agent(agent['id'], agent['name'])
        results.append(result)
        time.sleep(2)  # Delay untuk menghindari rate limit
    
    # Generate reports
    markdown_report = generate_markdown(results)
    json_report = generate_json(results)
    
    # Save to files
    with open('STATS.md', 'w', encoding='utf-8') as f:
        f.write(markdown_report)
    
    with open('stats.json', 'w', encoding='utf-8') as f:
        f.write(json_report)
    
    print("\n✅ Reports generated: STATS.md and stats.json")
    print("\n" + markdown_report)

if __name__ == "__main__":
    main()
