import requests
import json
import os
from datetime import datetime

# ========== KONFIGURASI ==========
# GANTI DENGAN WALLET AGEN KAMU
AGENT_WALLETS = {
    "Quantiva Intelligence": "0xb9868eb3bb740d4d61c0dc1feb4bed6fb58f76e7",
    "Nexora Analytics AI": "0xB9868eB3Bb740d4d61c0Dc1fEb4Bed6FB58f76E7",  # GANTI
    "DataQuant Pro": "0xC222Ce890859E07D8b31a3ccb8C186ebA9914948",         # GANTI
    "DataAnalyst Pro": "0xe16b3f9617aae564c7314bb555c052ce6524fd3f",
    "InsightForge AI": "0x32D9b8E82aa07F77bcBB648Ccf534ED41A782b32",       # GANTI
    "StoryWeaver AI": "0x65f20d80f2817cb4524bfc0f3bc37173da6b1058",
}

# Konfigurasi Superfluid (Base Chain)
SUPERFLUID_API = "https://subgraph.satsuma-prod.com/3e3c05c7d685/superfluid-mainnet/api"
TOKEN_ADDRESS = "0xa69f80524381275A7fFdb3AE01c54150644c8792"  # GANTI dengan address token SUP di Base
# =================================

def get_superfluid_stats(wallet_address):
    """Ambil data balance & net flow dari Superfluid subgraph"""
    
    query = """
    {
      account(id: "%s") {
        id
        tokenBalances {
          token {
            id
            symbol
            name
            decimals
          }
          totalBalance
          totalNetFlowRate
        }
      }
    }
    """ % wallet_address.lower()
    
    try:
        response = requests.post(
            SUPERFLUID_API,
            json={"query": query},
            headers={"Content-Type": "application/json"},
            timeout=30
        )
        
        if response.status_code == 200:
            data = response.json()
            account = data.get("data", {}).get("account")
            
            if account and account.get("tokenBalances"):
                balance_data = account["tokenBalances"][0]
                balance_raw = int(balance_data["totalBalance"])
                decimals = int(balance_data["token"]["decimals"])
                balance = balance_raw / (10 ** decimals)
                
                net_flow_raw = int(balance_data["totalNetFlowRate"])
                net_flow_per_month = net_flow_raw * 30 * 24 * 3600 / (10 ** decimals)
                
                return {
                    "token_symbol": balance_data["token"]["symbol"],
                    "balance": round(balance, 4),
                    "net_flow_per_month": round(net_flow_per_month, 4),
                    "status": "active" if net_flow_per_month != 0 else "idle"
                }
        
        return {"error": f"HTTP {response.status_code}", "status": "error"}
        
    except Exception as e:
        return {"error": str(e), "status": "error"}

def get_token_price(token_symbol):
    """Ambil harga token dari CoinGecko (opsional)"""
    try:
        url = f"https://api.coingecko.com/api/v3/simple/price?ids=superfluid&vs_currencies=usd"
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            data = response.json()
            return data.get("superfluid", {}).get("usd", 0)
    except:
        pass
    return 0

def generate_markdown(stats, price):
    """Generate laporan markdown"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    markdown = f"""# 💰 Superfluid Streaming Stats

**Last Update:** {timestamp} UTC
**Token Price:** ${price:.4f} (SUP)

| Agent | Balance | Balance (USD) | Net Flow / Month | Status |
|-------|---------|---------------|------------------|--------|
"""
    
    for agent_name, data in stats.items():
        if "error" in data:
            markdown += f"| {agent_name} | ❌ Error | - | - | {data['error']} |\n"
        else:
            balance_usd = data['balance'] * price
            flow_usd = data['net_flow_per_month'] * price
            markdown += f"| {agent_name} | {data['balance']:.4f} {data['token_symbol']} | ${balance_usd:.2f} | +{data['net_flow_per_month']:.2f} {data['token_symbol']}/mo (${flow_usd:.2f}) | {data['status']} |\n"
    
    markdown += f"""
---
<sub>Auto-generated by GitHub Actions • {timestamp} UTC</sub>
"""
    return markdown

def main():
    print(f"🚀 Fetching Superfluid stats for {len(AGENT_WALLETS)} agents...")
    
    # Ambil harga token SUP
    price = get_token_price("superfluid")
    
    # Ambil data untuk setiap wallet
    results = {}
    for name, wallet in AGENT_WALLETS.items():
        if wallet and not wallet.startswith("0x..."):
            print(f"📡 Checking {name}...")
            results[name] = get_superfluid_stats(wallet)
        else:
            results[name] = {"error": "Wallet not configured", "status": "pending"}
    
    # Generate markdown dan JSON
    markdown = generate_markdown(results, price)
    json_output = {
        "timestamp": datetime.now().isoformat(),
        "token_price_usd": price,
        "agents": results
    }
    
    with open("STREAMING_STATS.md", "w", encoding="utf-8") as f:
        f.write(markdown)
    
    with open("streaming-stats.json", "w", encoding="utf-8") as f:
        json.dump(json_output, f, indent=2)
    
    print("\n✅ Reports generated: STREAMING_STATS.md and streaming-stats.json")
    print(markdown)

if __name__ == "__main__":
    main()
